services:
  db:
    container_name: auth-db
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/app/src


  pgadmin:
    container_name: nestjs-pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    depends_on:
      - db